import type { Post } from "./api";

export const mockUser = {
  id: 1,
  email: "student@university.edu",
  name: "John Doe",
  role: "student",
  university: "Stanford University",
  phone: "+1 (555) 123-4567",
};

export const mockPosts: Post[] = [
  {
    id: 1,
    title: "MacBook Pro 2021 - 16 inch",
    description: "Excellent condition, barely used. Perfect for coding and design work. Comes with original charger and box.",
    price: "1299.99",
    category: "electronics",
    seller_id: 2,
    university: "Stanford University",
    images: [],
    views: 245,
    status: "active",
    contact_method: "email",
    location: "Campus Library",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Sarah Chen",
    seller_email: "sarah@university.edu",
  },
  {
    id: 2,
    title: "Calculus Textbook - Stewart 8th Edition",
    description: "MATH 41 textbook in great condition. No highlighting or writing inside. Perfect for next semester.",
    price: "75.00",
    category: "textbooks",
    seller_id: 3,
    university: "Stanford University",
    images: [],
    views: 189,
    status: "active",
    contact_method: "email",
    course: "MATH 41",
    location: "Main Quad",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Mike Johnson",
    seller_email: "mike@university.edu",
  },
  {
    id: 3,
    title: "Stanford vs UCLA Football Tickets",
    description: "2 tickets for the big game! Section 15, Row 20. Great seats near the 50-yard line.",
    price: "150.00",
    category: "game-tickets",
    seller_id: 4,
    university: "Stanford University",
    images: [],
    views: 342,
    status: "active",
    contact_method: "both",
    event: "Stanford vs UCLA",
    location: "Stanford Stadium",
    event_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Alex Martinez",
    seller_email: "alex@university.edu",
  },
  {
    id: 4,
    title: "Organic Chemistry Textbook",
    description: "CS 106A textbook, 3rd edition. Used for one semester, excellent condition.",
    price: "65.00",
    category: "textbooks",
    seller_id: 5,
    university: "Stanford University",
    images: [],
    views: 156,
    status: "active",
    contact_method: "email",
    course: "CS 106A",
    location: "Engineering Quad",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Emily Davis",
    seller_email: "emily@university.edu",
  },
  {
    id: 5,
    title: "Gaming Chair - Ergonomic",
    description: "Comfortable gaming chair, perfect for long study sessions. Adjustable height and lumbar support.",
    price: "120.00",
    category: "furniture",
    seller_id: 6,
    university: "Stanford University",
    images: [],
    views: 98,
    status: "active",
    contact_method: "phone",
    location: "Dorm Room 204",
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "David Kim",
    seller_email: "david@university.edu",
  },
  {
    id: 6,
    title: "Stanford vs USC Basketball Tickets",
    description: "4 tickets available for the basketball game. Section 8, great view of the court!",
    price: "80.00",
    category: "game-tickets",
    seller_id: 7,
    university: "Stanford University",
    images: [],
    views: 267,
    status: "active",
    contact_method: "email",
    event: "Stanford vs USC",
    location: "Maples Pavilion",
    event_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Jessica Wang",
    seller_email: "jessica@university.edu",
  },
  {
    id: 7,
    title: "iPad Air 4th Gen",
    description: "Like new iPad Air, 256GB. Perfect for note-taking and studying. Comes with Apple Pencil.",
    price: "550.00",
    category: "electronics",
    seller_id: 8,
    university: "Stanford University",
    images: [],
    views: 312,
    status: "active",
    contact_method: "both",
    location: "Tresidder Union",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Ryan Patel",
    seller_email: "ryan@university.edu",
  },
  {
    id: 8,
    title: "Physics Textbook - Halliday & Resnick",
    description: "PHYSICS 41 textbook, 10th edition. Minimal wear, all pages intact.",
    price: "85.00",
    category: "textbooks",
    seller_id: 9,
    university: "Stanford University",
    images: [],
    views: 134,
    status: "active",
    contact_method: "email",
    course: "PHYSICS 41",
    location: "Science Building",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Lisa Anderson",
    seller_email: "lisa@university.edu",
  },
  {
    id: 9,
    title: "Nike Running Shoes - Size 10",
    description: "Hardly worn, perfect condition. Great for running or gym workouts.",
    price: "60.00",
    category: "clothing",
    seller_id: 10,
    university: "Stanford University",
    images: [],
    views: 87,
    status: "active",
    contact_method: "email",
    location: "Athletic Center",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Tom Wilson",
    seller_email: "tom@university.edu",
  },
  {
    id: 10,
    title: "Spring Concert Tickets",
    description: "2 tickets for the annual spring concert. General admission, great event!",
    price: "45.00",
    category: "game-tickets",
    seller_id: 11,
    university: "Stanford University",
    images: [],
    views: 201,
    status: "active",
    contact_method: "phone",
    event: "Spring Concert",
    location: "Campus Quad",
    event_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    seller_name: "Maria Garcia",
    seller_email: "maria@university.edu",
  },
];

